CREATE TABLE IF NOT EXISTS `wp_prt_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `salutation` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(150) NULL,
  `lastname` VARCHAR(150) NULL,
  `phone` VARCHAR(60) NULL,
  `email` VARCHAR(150) NULL,
  `address` VARCHAR(300) NULL,
  `wohnflache` INT NULL,
  `zimmer` DECIMAL(1) NULL,
  `baujahr` VARCHAR(45) NULL,
  `grundflache` INT NULL,
  `etage` INT NULL,
  `erschlossen` VARCHAR(45) NULL,
  `bebauung` VARCHAR(45) NULL,
  `zuschnitt` VARCHAR(45) NULL,
  `resultAbsolute` DECIMAL(12,2) NULL,
  `lowAbsolute` DECIMAL(12,2) NULL,
  `highAbsolute` DECIMAL(12,2) NULL,
  `resultPerSqm` DECIMAL(12,2) NULL,
  `lowPerSqm` DECIMAL(12,2) NULL,
  `highPerSqm` DECIMAL(12,2) NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`));

CREATE TABLE IF NOT EXISTS `wp_prt_statistics` (
  `id` VARCHAR(100) NOT NULL,
  `wp_username` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  `country` VARCHAR(4) NULL,
  `city` VARCHAR(150) NULL,
  `user_agent` VARCHAR(150) NULL,
  `user_browser` VARCHAR(60) NULL,
  `user_os` VARCHAR(45) NULL,
  `user_device` VARCHAR(45) NULL,
  `user_lang` VARCHAR(10) NULL,
  `last_activity` VARCHAR(200) NULL,
  `finished` TINYINT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`));
